name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        ruby-version: ['2.7.2']

    steps:
      - uses: actions/checkout@v3
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake db:migrate
        env:
          RAILS_ENV: test
          DATABASE_HOST: 'localhost'
          DATABASE_USERNAME: 'postgres'
          DATABASE_PASSWORD: 'postgres'
      - name: Run tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_HOST: 'localhost'
          DATABASE_USERNAME: 'postgres'
          DATABASE_PASSWORD: 'postgres'
